$(function() {
  var get0 = "ぼんやり男";
  var get1 = "ハキハキ男";
  var get2 = "コワイ男";
  var get3 = "キザ男";
  var get4 = "ふつう女";
  var get5 = "げんき女";
  var get6 = "オトナ女";
  var get7 = "アネキ女";
  var get8 = "住民全員";
  var get9 = "たぬき商店";
  var get10 = "たぬきマイル交換";
  var get13 = "フーコ";
  var balloon =　"風船<br>(季節限定)"
  var info = [
    {category: 1,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x6\nきのえだ x2",image: "FtrSnowman_Remake_0_0",name: "３だんゆきだるま",get: "ゆきだるま"},
    {category: 1,series: 99,obtain: 7,make: "もくざい x5\nかたいもくざい x5\nやわらかいもくざい x5\nてっこうせき x3\nちいさなDIYさぎょうだい x1",image: "FtrWorkbench_Remake_0_0",name: "DIYさぎょうだい",get: get7},
    {category: 3,series: 99,obtain: 8,make: "あおいバラ x10",image: "FtrDoorOrnamentWreathRoseUrtraRare",name: "あおいバラのリース",get: get8},
    {category: 1,series: 6,obtain: 12,make: "もみじのはっぱ x3\nざっそう x4",image: "FtrFallenleavesRed",name: "あかいおちば",get: balloon},
    {category: 2,series: 99,obtain: 11,make: "あきカン x1\nもくざい x1\nてっこうせき x1",image: "FtrKalimbaCan_Remake_0_0",name: "あきかんカリンバ",get: "あきカンを釣る"},
    {category: 0,series: 99,obtain: 9,make: "ショボいあみ x1\nてっこうせき x1",image: "ToolNetNormal_Remake_0_0",name: "あみ",get: get9},
    {category: 6,series: 99,obtain: 99,make: "ざっそう x10\nきのえだ x5\nいし x2",image: "ItemFenceIkegaki",name: "いけがき",get: "たぬきち(アースデイ)"},
    {category: 6,series: 99,obtain: 10,make: "いし x4",image: "ItemFenceStone",name: "いしかべ",get: get10},
    {category: 1,series: 99,obtain: 9,make: "ねんど x8\nてっこうせき x2\nもくざい x6",image: "FtrStoneoven_Remake_0_0",name: "いしがま",get: get9},
    {category: 4,series: 99,obtain: 3,make: "いし x10",image: "RoomTexWallBasement00",name: "いしのかべ",get: get3},
    {category: 1,series: 99,obtain: 6,make: "いし x10",image: "FtrStonewaterbowl_Remake_0_0",name: "いしのみずうけ",get: get6},
    {category: 1,series: 1,obtain: 12,make: "いし x10\nさくらのはなびら x3",image: "FtrStonewaterbowlSakura",name: "いしのみずうけ～さくら～",get: balloon},
    {category: 1,series: 6,obtain: 12,make: "いし x10\nもみじのはっぱ x3",image: "FtrStonewaterbowlAutumun",name: "いしのみずうけ～もみじ～",get: balloon},
    {category: 0,series: 99,obtain: 9,make: "ショボいオノ x1\nもくざい x3",image: "ToolAxeStoneNormal",name: "いしのオノ",get: get9},
    {category: 1,series: 99,obtain: 9,make: "いし x3",image: "FtrStoneChair",name: "いしのスツール",get: get9},
    {category: 1,series: 99,obtain: 0,make: "いし x8",image: "FtrStoneTable",name: "いしのテーブル",get: get0},
    {category: 3,series: 99,obtain: 2,make: "かたいもくざい x5",image: "FtrSignboardWood_Remake_0_0",name: "いちまいいたのかんばん",get: get2},
    {category: 1,series: 99,obtain: 1,make: "もくざい x10\nかたいもくざい x7",image: "FtrDoghouse_Remake_0_0",name: "いぬごや",get: get1},
    {category: 1,series: 99,obtain: 9,make: "バンブー x2\nてっこうせき x5\nねんど x4\nかたいもくざい x5",image: "FtrIrori",name: "いろり",get: get9},
    {category: 5,series: 0,obtain: 99,make: "いわのたまご x2",image: "CapHatEggrock0",name: "いわのたまごのから",get: "いわのたまごを集める"},
    {category: 5,series: 0,obtain: 99,make: "いわのたまご x2",image: "ShoesLowcutEggrock0",name: "いわのたまごのくつ",get: "いわのたまごを集める"},
    {category: 5,series: 0,obtain: 99,make: "いわのたまご x3",image: "TopsTexOnepieceRibNEggrock0",name: "いわのたまごのふく",get: "いわのたまごを集める"},
    {category: 1,series: 11,obtain: 13,make: "ほしのかけら x5\nいし x10",image: "FtrMeteo",name: "いんせき",get: get13},
    {category: 4,series: 11,obtain: 13,make: "ほしのかけら x5\nおおきなほしのかけら x1",image: "RoomSpWallSF00",name: "うちゅうせんのかべ",get: get13},
    {category: 4,series: 11,obtain: 13,make: "ほしのかけら x5\nおおきなほしのかけら x1",image: "RoomSpFloorSF00",name: "うちゅうせんのゆか",get: get13},
    {category: 4,series: 3,obtain: 12,make: "なつのかいがら x3\nサンゴ x3",image: "RoomSpFloorFishTank00",name: "うみのそこのゆか",get: balloon},
    {category: 1,series: 99,obtain: 5,make: "しろいヒヤシンス x3\nあかいコスモス x3\nきいろいバラ x3\nもくざい x8\nてっこうせき x2",image: "FtrGardenwagon_Remake_0_0",name: "えんげいワゴン",get: get5},
    {category: 4,series: 99,obtain: 3,make: "きんこうせき x4",image: "RoomTexWallGold00",name: "おうごんのかべ",get: get3},
    {category: 2,series: 99,obtain: 3,make: "きんこうせき x2",image: "FtrGoldCandlestand",name: "おうごんのしょくだい",get: get3},
    {category: 2,series: 99,obtain: 6,make: "きんこうせき x1",image: "FtrGoldDishes",name: "おうごんのしょっき",get: get6},
    {category: 3,series: 99,obtain: 3,make: "きんこうせき x1\nてっこうせき x3",image: "FtrGearWallGold",name: "おうごんのはぐるま",get: get3},
    {category: 1,series: 99,obtain: 3,make: "きんこうせき x8",image: "FtrGoldCoffin",name: "おうごんのひつぎ",get: get3},
    {category: 4,series: 99,obtain: 3,make: "きんこうせき x4",image: "RoomTexFloorGold00",name: "おうごんのゆか",get: get3},
    {category: 0,series: 99,obtain: 13,make: "きんこうせき x2\nほしのかけら x3",image: "ToolStickGolden",name: "おうごんのステッキ",get: get13},
    {category: 1,series: 99,obtain: 6,make: "きんこうせき x6",image: "FtrGoldWC",name: "おうごんのトイレ",get: get6},
    {category: 1,series: 99,obtain: 6,make: "きんこうせき x5",image: "FtrGoldbench",name: "おうごんのベンチ",get: get6},
    {category: 1,series: 6,obtain: 12,make: "まつぼっくり x5\nどんぐり x4\nもみじのはっぱ x4\nきのえだ x8\nねんど x4",image: "FtrNutTreeL_Remake_0_0",name: "おおきなきのみのツリー",get: balloon},
    {category: 1,series: 8,obtain: 12,make: "あかいオーナメント x6\nあおいオーナメント x6\nきんのオーナメント x4\nもくざい x5\nねんど x5",image: "FtrTreeXmasL_Remake_0_0",name: "おおきなクリスマスツリー",get: balloon},
    {category: 6,series: 99,obtain: 8,make: "ハチのす x1\nざっそう x3",image: "Medicine",name: "おくすり",get: get8},
    {category: 1,series: 6,obtain: 12,make: "まつぼっくり x3\nざっそう x5",image: "FtrFallenleaves",name: "おちば",get: balloon},
    {category: 1,series: 6,obtain: 12,make: "まつぼっくり x3\nざっそう x5\nきのえだ x3",image: "FtrFallenleavesfire_Remake_0_0",name: "おちばのたきび",get: balloon},
    {category: 1,series: 6,obtain: 12,make: "もみじのはっぱ x3\nもくざい x3",image: "FtrFallenleavesChairS_Remake_0_0",name: "おちばスツール",get: balloon},
    {category: 6,series: 99,obtain: 1,make: "ざっそう x4\nきのえだ x6",image: "SeedPitfall",name: "おとしあなのタネ",get: get1},
    {category: 1,series: 1,obtain: 12,make: "さくらのはなびら x6\nかたいもくざい x4",image: "FtrSakuraLantern_Remake_0_0",name: "おはなみのちょうちん",get: balloon},
    {category: 1,series: 1,obtain: 12,make: "さくらのはなびら x10",image: "FtrSakuraPicnicset",name: "おはなみセット",get: balloon},
    {category: 4,series: 99,obtain: 11,make: "あきカン x2\nながぐつ(ゴミ) x2\nタイヤ x2",image: "RoomTexFloorGarbage00",name: "おへやのゆか",get: "ゴミを釣る"},
    {category: 5,series: 11,obtain: 13,make: "ほしのかけら x5",image: "CapCostumeStar0",name: "おほしさまのあたま",get: get13},
    {category: 2,series: 8,obtain: 12,make: "きんのオーナメント x2\nかたいもくざい x1",image: "FtrFestivaltop",name: "おまつりのコマ",get: balloon},
    {category: 1,series: 99,obtain: 2,make: "てっこうせき x5",image: "FtrScreenCage_Remake_0_0",name: "おり",get: get2},
    {category: 1,series: 9,obtain: 0,make: "シャコガイ x5\nいし x3",image: "FtrShellFountain_Remake_0_0",name: "かいがらのふんすい",get: get0},
    {category: 1,series: 9,obtain: 0,make: "エビスガイ x3\nホネガイ x3\nサンドダラー x3\nサンゴ x3\nシャコガイ x3\nタカラガイ x3",image: "FtrShellArch_Remake_0_0",name: "かいがらのアーチ",get: get0},
    {category: 1,series: 9,obtain: 7,make: "ホネガイ x4\nホラガイ x4",image: "FtrShellScreen_Remake_0_0",name: "かいがらのスクリーン",get: get7},
    {category: 1,series: 9,obtain: 7,make: "タカラガイ x5",image: "FtrShellStoolS_Remake_0_0",name: "かいがらのスツール",get: get7},
    {category: 0,series: 3,obtain: 12,make: "なつのかいがら x3\nほしのかけら x3",image: "ToolStickShell",name: "かいがらのステッキ",get: balloon},
    {category: 2,series: 9,obtain: 7,make: "ホラガイ x3\nてっこうせき x2",image: "FtrShellMusic_Remake_0_0",name: "かいがらのスピーカー",get: get7},
    {category: 1,series: 9,obtain: 5,make: "サンドダラー x7\nねんど x3",image: "FtrShellTableL_Remake_0_0",name: "かいがらのテーブル",get: get5},
    {category: 1,series: 9,obtain: 5,make: "シャコガイ x5\nねんど x3\nいし x4",image: "FtrShellBedW_Remake_0_0",name: "かいがらのベッド",get: get5},
    {category: 4,series: 9,obtain: 5,make: "シャコガイ x3",image: "RugOtherShellM00",name: "かいがらのラグ",get: get5},
    {category: 2,series: 9,obtain: 7,make: "シャコガイ x2\nねんど x3",image: "FtrShellLamp_Remake_0_0",name: "かいがらのランプ",get: get7},
    {category: 3,series: 3,obtain: 12,make: "なつのかいがら x1\nエビスガイ x1\nサンドダラー x1\nサンゴ x1\nシャコガイ x1\nタカラガイ x1",image: "FtrDoorOrnamentWreathShell",name: "かいがらのリース",get: balloon},
    {category: 5,series: 3,obtain: 12,make: "シャコガイ x2\nなつのかいがら x6",image: "BagShoulderShell0",name: "かいがらポシェット",get: balloon},
    {category: 1,series: 99,obtain: 2,make: "きのえだ x3\nざっそう x5",image: "FtrScarecrow",name: "かかし",get: get2},
    {category: 1,series: 99,obtain: 2,make: "てっこうせき x3",image: "FtrUmbrellastand_Remake_0_0",name: "かさたて",get: get2},
    {category: 5,series: 99,obtain: 2,make: "ざっそう x10",image: "CapHatAjiroBeige",name: "かさぼうし",get: get2},
    {category: 3,series: 99,obtain: 1,make: "かせき x1\nいし x2",image: "FtrDoorOrnamentFossil_Remake_0_0",name: "かせきのドアプレート",get: get1},
    {category: 3,series: 99,obtain: 9,make: "ざっそう x5\nねんど x5",image: "FtrLeafWall_Remake_0_0",name: "かべかけのはっぱ",get: get9},
    {category: 2,series: 99,obtain: 2,make: "ねんど x5",image: "FtrKame_Remake_0_0",name: "かめ",get: get2},
    {category: 1,series: 8,obtain: 12,make: "あかいオーナメント x3\nあおいオーナメント x3\n x3\nもくざい x5",image: "FtrTreeXmasS_Remake_0_0",name: "かわいいクリスマスツリー",get: balloon},
    {category: 1,series: 6,obtain: 12,make: "どんぐり x3\nざっそう x5",image: "FtrFallenleavesYellow",name: "きいろのおちば",get: balloon},
    {category: 0,series: 99,obtain: 13,make: "きのえだ x5\nほしのかけら x3",image: "ToolStickTree",name: "きのえだのステッキ",get: get13},
    {category: 3,series: 99,obtain: 7,make: "きのえだ x10",image: "FtrDoorOrnamentWreathBranch",name: "きのえだのリース",get: get7},
    {category: 1,series: 4,obtain: 12,make: "まつぼっくり x4\nどんぐり x5\nもみじのはっぱ x5\nきのえだ x15",image: "FtrNutArch_Remake_0_0",name: "きのみのアーチ",get: balloon},
    {category: 3,series: 4,obtain: 12,make: "まつぼっくり x2\nどんぐり x3\nきのえだ x3",image: "FtrNutMobile_Remake_0_0",name: "きのみのモビール",get: balloon},
    {category: 2,series: 4,obtain: 12,make: "どんぐり x6\nねんど x4",image: "FtrNutLamp_Remake_0_0",name: "きのみのランプ",get: balloon},
    {category: 0,series: 99,obtain: 99,make: "あみ x1\nきんこうせき x1",image: "ToolNetGold",name: "きんのあみ",get: "ムシ図鑑完成"},
    {category: 0,series: 99,obtain: 99,make: "つりざお x1\nきんこうせき x1",image: "ToolFishingrodGold",name: "きんのつりざお",get: "サカナ図鑑完成"},
    {category: 2,series: 99,obtain: 6,make: "きんこうせき x3",image: "FtrGoldbar",name: "きんののべぼう",get: get6},
    {category: 2,series: 99,obtain: 6,make: "きんこうせき x2\nまねきねこ x1",image: "FtrManekinekoGold",name: "きんのまねきねこ",get: get6},
    {category: 2,series: 99,obtain: 0,make: "きんこうせき x3",image: "FtrFishArowanaGold",name: "きんのアロワナ",get: get0},
    {category: 0,series: 99,obtain: 99,make: "オノ x1\nきんこうせき x1",image: "ToolAxeGold",name: "きんのオノ",get: "オノを100回壊す"},
    {category: 0,series: 99,obtain: 99,make: "ジョウロ x1\nきんこうせき x1",image: "ToolWateringGold",name: "きんのジョウロ",get: "島の評判☆5"},
    {category: 2,series: 99,obtain: 0,make: "きんこうせき x3",image: "FtrInsectKabutomushiGold",name: "きんのスカラベ",get: get0},
    {category: 0,series: 99,obtain: 99,make: "スコップ x1\nきんこうせき x1",image: "ToolScoopGold",name: "きんのスコップ",get: "ジョニーを30回助ける"},
    {category: 3,series: 99,obtain: 8,make: "きんのバラ x10",image: "FtrDoorOrnamentWreathRoseGold",name: "きんのバラのリース",get: get8},
    {category: 0,series: 99,obtain: 99,make: "パチンコ x1\nきんこうせき x1",image: "ToolSlingshotGold",name: "きんのパチンコ",get: "風船を300回割る"},
    {category: 4,series: 99,obtain: 3,make: "きんこうせき x2\nふすま x1",image: "RoomTexWallFusumaGorgeous00",name: "きんぱくのふすま",get: get3},
    {category: 4,series: 11,obtain: 13,make: "ほしのかけら x5\nおおきなほしのかけら x1",image: "RoomSpFloorGalaxy00",name: "ぎんがけいのゆか",get: get13},
    {category: 5,series: 99,obtain: 4,make: "ざっそう x20",image: "BagBackpackGrass0",name: "くさあみリュック",get: get4},
    {category: 1,series: 99,obtain: 5,make: "くまのダイちゃん x1\nくまのナミちゃん x1\nくまのチビちゃん x1",image: "FtrBearXL_Remake_0_0",name: "くまのトクダイちゃん",get: get5},
    {category: 1,series: 11,obtain: 13,make: "ほしのかけら x10\nてっこうせき x10\nタイヤ x4",image: "FtrMoonrover",name: "げつめんいどうしゃ",get: get13},
    {category: 4,series: 11,obtain: 13,make: "ほしのかけら x5\nおおきなほしのかけら x1",image: "RoomTexFloorLunar00",name: "げつめんのゆか",get: get13},
    {category: 4,series: 6,obtain: 12,make: "もみじのはっぱ x10\nもくざい x5\nざっそう x5",image: "RoomSpWallAutumun00",name: "こうようのかべ",get: balloon},
    {category: 1,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x4",image: "FtrIcePillar_Remake_0_0",name: "こおりのはしら",get: "ゆきだるま"},
    {category: 1,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x10",image: "FtrIceGate_Remake_0_0",name: "こおりのアーチ",get: "ゆきだるま"},
    {category: 1,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1ゆきのけっしょう x4",image: "FtrIceArt_Remake_0_0",name: "こおりのアート",get: "ゆきだるま"},
    {category: 1,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x4",image: "FtrIceChairS_Remake_0_0",name: "こおりのイス",get: "ゆきだるま"},
    {category: 1,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x5",image: "FtrIceCounter_Remake_0_0",name: "こおりのカウンター",get: "ゆきだるま"},
    {category: 0,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nほしのかけら x3",image: "ToolStickSnow",name: "こおりのステッキ",get: "ゆきだるま"},
    {category: 1,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x8",image: "FtrIceTree_Remake_0_0",name: "こおりのツリー",get: "ゆきだるま"},
    {category: 1,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x8",image: "FtrIceTableL_Remake_0_0",name: "こおりのテーブル",get: "ゆきだるま"},
    {category: 1,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x6",image: "FtrIceScreen_Remake_0_0",name: "こおりのパーテーション",get: "ゆきだるま"},
    {category: 1,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x10",image: "FtrIceBedW_Remake_0_0",name: "こおりのベッド",get: "ゆきだるま"},
    {category: 1,series: 99,obtain:0 ,make: "いし x15\nざっそう x15",image: "FtrGardenrockMoss",name: "こけむしたにわいし",get: get0},
    {category: 4,series: 99,obtain: 3,make: "やわらかいもくざい x15",image: "RoomTexWallHerringbone01",name: "こげちゃのヘリンボーンのかべ",get: get3},
    {category: 5,series:99 ,obtain: 4,make: "ざっそう x7",image: "BottomsTexSkirtBoxGrass0",name: "こしみの",get: get4},
    {category: 1,series: 99,obtain: 2,make: "てっこうせき x8\nもくざい x2\nたきび x1",image: "FtrGoemonburo",name: "ごえもんぶろ",get: get2},
    {category: 4,series: 1,obtain: 12,make: "さくらのはなびら x10\nかたいもくざい x5",image: "RoomSpWallSakura00",name: "さくらなみきのかべ",get: balloon},
    {category: 1,series: 1,obtain: 12,make: "さくらのはなびら x8\nきのえだ x4\nねんど x5",image: "FtrSakuraBranch",name: "さくらのえだ",get: balloon},
    {category: 5,series: 1,obtain: 12,make: "さくらのはなびら x7",image: "UmbrellaCherryblossom0Cropped",name: "さくらのかさ",get: balloon},
    {category: 4,series: 1,obtain: 12,make: "さくらのはなびら x10\nざっそう x20",image: "RoomTexFloorSakura00",name: "さくらのじゅうたん",get: balloon},
    {category: 1,series: 1,obtain: 12,make: "さくらのはなびら x5",image: "FtrSakuraPetal",name: "さくらのはなびらのやま",get: balloon},
    {category: 2,series: 1,obtain: 12,make: "さくらのはなびら x6\nかたいもくざい x2\nざっそう x3\nねんど x3",image: "FtrBonsaiSakura",name: "さくらのぼんさい",get: balloon},
    {category: 4,series: 1,obtain: 12,make: "さくらのはなびら x5\nもくざい x10",image: "RoomTexWallSolidWood00",name: "さくらのウッドウォール",get: balloon},
    {category: 4,series: 1,obtain: 12,make: "さくらのはなびら x5\nもくざい x10",image: "RoomTexFloorSolidWood00",name: "さくらのウッドフローリング",get: balloon},
    {category: 0,series: 1,obtain: 12,make: "さくらのはなびら x3\nほしのかけら x3",image: "ToolStickCherryblossom",name: "さくらのステッキ",get: balloon},
    {category: 5,series: 1,obtain: 12,make: "さくらのはなびら x6",image: "BagShoulderCherryblossoms0",name: "さくらのポシェット",get: balloon},
    {category: 5,series: 99,obtain: 5,make: "さくらんぼ x7",image: "UmbrellaCherry0Cropped",name: "さくらんぼのかさ",get: get5},
    {category: 4,series: 99,obtain: 5,make: "さくらんぼ x20",image: "RoomTexWallCherry00",name: "さくらんぼのかべがみ",get: get5},
    {category: 5,series: 99,obtain: 5,make: "さくらんぼ x8",image: "TopsTexOnepieceAlineNCherry0",name: "さくらんぼのふく",get: get5},
    {category: 5,series: 99,obtain: 5,make: "さくらんぼ x5",image: "CapHatCherry0",name: "さくらんぼのぼうし",get: get5},
    {category: 2,series: 99,obtain: 5,make: "さくらんぼ x10\nてっこうせき x2",image: "FtrFruitsMusic_Remake_0_0",name: "さくらんぼのスピーカー",get: get5},
    {category: 4,series: 99,obtain: 5,make: "さくらんぼ x6",image: "RugOtherCherryM00",name: "さくらんぼのラグ",get: get5},
    {category: 3,series: 99,obtain: 5,make: "さくらんぼ x10\nねんど x2",image: "FtrFruitsLampW_Remake_0_0",name: "さくらんぼのランプ",get: get5},
    {category: 3,series: 1,obtain: 12,make: "さくらのはなびら x5",image: "FtrSakuraClockW_Remake_0_0",name: "さくらクロック",get: balloon},
    {category: 5,series: 99,obtain: 3,make: "ざっそう x10",image: "CapHatSandogasa0",name: "さんどがさ",get: get3},
    {category: 2,series: 99,obtain: 5,make: "ざっし x6",image: "FtrMagagine_Remake_0_0",name: "ざっしのたば",get: get5},
    {category: 1,series: 99,obtain: 2,make: "ざぶとん x3",image: "FtrCushionJapanPile_Remake_0_0",name: "ざぶとんのやま",get: get2},
    {category: 3,series: 99,obtain: 0,make: "やわらかいもくざい x8",image: "FtrHuntingtrophy_Remake_0_0",name: "しかのオブジェ",get: get0},
    {category: 1,series: 2,obtain: 2,make: "バンブー x3\nいし x8\nざっそう x3",image: "FtrShishiodoshi_Remake_0_0",name: "ししおどし",get: get2},
    {category: 4,series: 99,obtain: 5,make: "ざっそう x30",image: "RoomTexFloorLawn00",name: "しばふのゆか",get: get5},
    {category: 5,series: 2,obtain: 12,make: "はるのわかたけ x6",image: "BagBackpackBasket0",name: "しょいこ",get: balloon},
    {category: 1,series: 99,obtain: 10,make: "いし x10\nねんど x10",image: "FtrTetrapod",name: "しょうはブロック",get: get10},
    {category: 2,series: 99,obtain: 3,make: "ちらばったかみ x1",image: "FtrOfficePapers_Remake_0_0",name: "しょるいのやま",get: get3},
    {category: 5,series: 0,obtain: 99,make: "じめんのたまご x2",image: "CapHatEggground0",name: "じめんのたまごのから",get: "じめんのたまごを集める"},
    {category: 5,series: 0,obtain: 99,make: "じめんのたまご x2",image: "CapHatEggground0",name: "じめんのたまごのくつ",get: "じめんのたまごを集める"},
    {category: 5,series: 0,obtain: 99,make: "じめんのたまご x3",image: "TopsTexOnepieceRibNEggground0",name: "じめんのたまごのふく",get: "じめんのたまごを集める"},
    {category: 4,series: 99,obtain: 4,make: "ざっそう x15\nやわらかいもくざい x9",image: "RoomTexWallJukai00",name: "じゅかいなかべ",get: get4},
    {category: 1,series: 11,obtain: 13,make: "ほしのかけら x10\nてっこうせき x15",image: "FtrSatellite",name: "じんこうえいせい",get: get13},
    {category: 4,series: 3,obtain: 12,make: "なつのかいがら x3\nサンゴ x5",image: "RoomSpWallFishTank00",name: "すいちゅうのかべがみ",get: balloon},
    {category: 4,series: 99,obtain: 1,make: "エビスガイ x1\nホネガイ x1\nサンドダラー x1\nサンゴ x1\nシャコガイ x1\nタカラガイ x1",image: "RoomTexFloorSand00",name: "すなはまのゆか",get: get1},
    {category: 1,series: 99,obtain: 5,make: "もくざい x2\nやわらかいもくざい x5",image: "FtrBirdhouse_Remake_0_0",name: "すばこ",get: get5},
    {category: 2,series: 99,obtain: 6,make: "ねんど x3",image: "FtrDishesUnglazed_Remake_0_0",name: "すやきのしょっき",get: get6},
    {category: 2,series: 2,obtain: 12,make: "はるのわかたけ x6",image: "FtrBasketsteamer",name: "せいろ",get: balloon},
    {category: 5,series: 99,obtain: 1,make: "もくざい x3\nかたいもくざい x5",image: "BagBackpackWood0",name: "せおいばしご",get: get1},
    {category: 1,series: 99,obtain: 10,make: "かたいもくざい x4\nやわらかいもくざい x8",image: "FtrSignpostWorld_Remake_0_0",name: "せかいのみちしるべ",get: get10},
    {category: 1,series: 99,obtain: 3,make: "いし x24",image: "FtrSekishishi_Remake_0_0",name: "せきしし",get: get3},
    {category: 1,series: 99,obtain: 10,make: "いし x12",image: "FtrRockMonument_Remake_0_0",name: "せきひ",get: get10},
    {category: 2,series: 99,obtain: 9,make: "やわらかいもくざい x3",image: "FtrWashtub",name: "せんたくおけ",get: get9},
    {category: 1,series: 99,obtain: 1,make: "かたいもくざい x5\nてっこうせき x1",image: "FtrWorkbenchStump",name: "そぼくなDIYさぎょうだい",get: get1},
    {category: 1,series: 99,obtain: 9,make: "もくざい x6\nねんど x4\nてっこうせき x1",image: "FtrWashstandBowl_Remake_0_0",name: "そぼくなせんめんだい",get: get9},
    {category: 1,series: 99,obtain: 1,make: "もくざい x6",image: "FtrSignWood_Remake_0_0",name: "そぼくなもくせいかんばん",get: get1},
    {category: 6,series: 99,obtain: 10,make: "やわらかいもくざい x6",image: "ItemFenceNatural",name: "そぼくなもくせいのさく",get: get10},
    {category: 1,series: 11,obtain: 13,make: "ほしのかけら x15\nてっこうせき x10",image: "FtrUFO",name: "そらとぶえんばん",get: get13},
    {category: 5,series: 0,obtain: 99,make: "そらとぶたまご x2",image: "CapHatEggsky0",name: "そらとぶたまごのから",get: "そらとぶたまごを集める"},
    {category: 5,series: 0,obtain: 99,make: "そらとぶたまご x2",image: "ShoesLowcutEggsky0",name: "そらとぶたまごのくつ",get: "そらとぶたまごを集める"},
    {category: 5,series: 0,obtain: 99,make: "そらとぶたまご x3",image: "TopsTexOnepieceRibNEggsky0",name: "そらとぶたまごのふく",get: "そらとぶたまごを集める"},
    {category: 1,series: 99,obtain: 2,make: "もくざい x8",image: "FtrSled_Remake_0_0",name: "そり",get: get2},
    {category: 1,series: 99,obtain: 2,make: "きのえだ x5\nもくざい x5",image: "FtrTorch",name: "たいまつ",get: get2},
    {category: 1,series: 99,obtain: 6,make: "いし x60",image: "FtrGardenrockTall",name: "たかいにわいし",get: get6},
    {category: 0,series: 99,obtain: 9,make: "やわらかいもくざい x5",image: "LongWoodenStick",name: "たかとびぼう",get: get9},
    {category: 1,series: 99,obtain: 99,make: "きのえだ x3",image: "FtrBonfire",name: "たきび",get: "たぬきち"},
    {category: 6,series: 2,obtain: 10,make: "バンブー x6",image: "ItemFenceBamboo",name: "たけがき",get: get10},
    {category: 3,series: 2,obtain: 1,make: "バンブー x1",image: "FtrBambooFlowerwall_Remake_0_0",name: "たけのいちりんざし",get: get1},
    {category: 1,series: 2,obtain: 6,make: "バンブー x7",image: "FtrBambooBasket_Remake_0_0",name: "たけのかご",get: get6},
    {category: 1,series: 2,obtain: 1,make: "バンブー x3",image: "FtrBambooCarstop_Remake_0_0",name: "たけのくるまどめ",get: get1},
    {category: 2,series: 2,obtain: 12,make: "はるのわかたけ x4\nたけのこ x5\nねんど x4",image: "FtrBambooshootLamp",name: "たけのこランプ",get: balloon},
    {category: 2,series: 2,obtain: 6,make: "バンブー x4",image: "FtrBambooLunch_Remake_0_0",name: "たけのべんとうばこ",get: get6},
    {category: 2,series: 2,obtain: 4,make: "バンブー x3",image: "FtrBambooBall_Remake_0_0",name: "たけのまり",get: get4},
    {category: 2,series: 2,obtain: 6,make: "バンブー x3\nねんど x2",image: "FtrBambooShelf_Remake_0_0",name: "たけのキャンドルホルダー",get: get6},
    {category: 1,series: 2,obtain: 6,make: "バンブー x15",image: "FtrBambooShelf_Remake_0_0",name: "たけのシェルフ",get: get6},
    {category: 1,series: 2,obtain: 2,make: "バンブー x7\nいし x6",image: "FtrBambooScreen_Remake_0_0",name: "たけのスクリーン",get: get2},
    {category: 1,series: 2,obtain: 6,make: "バンブー x5",image: "FtrBambooStool_Remake_0_0",name: "たけのスツール",get: get6},
    {category: 0,series: 2,obtain: 12,make: "はるのわかたけ x6\nほしのかけら x3",image: "ToolStickBamboo",name: "たけのステッキ",get: balloon},
    {category: 1,series: 2,obtain: 6,make: "バンブー x3\nてっこうせき x1",image: "FtrBambooMusic_Remake_0_0",name: "たけのスピーカー",get: get6},
    {category: 1,series: 2,obtain: 12,make: "はるのわかたけ x6",image: "FtrBambooSurprisedbox",name: "たけのビックリばこ",get: balloon},
    {category: 1,series: 2,obtain: 4,make: "バンブー x8",image: "FtrBambooLamp_Remake_0_0",name: "たけのフロアスタンド",get: get4},
    {category: 1,series: 2,obtain: 4,make: "バンブー x8",image: "FtrBambooChairL_Remake_0_0",name: "たけのベンチ",get: get4},
    {category: 6,series: 99,obtain: 10,make: "もくざい x8",image: "ItemFenceVerticalWood",name: "たていたのさく",get: get10},
    {category: 2,series: 99,obtain: 11,make: "ざっそう x10\nあきカン x1",image: "FtrPlantSucculents",name: "たにくしょくぶつ",get: "あきカンを釣る"},
    {category: 1,series: 99,obtain: 2,make: "ねんど x6",image: "FtrOrnamentTanuki",name: "たぬきのおきもの",get: get2},
    {category: 5,series: 0,obtain: 99,make: "じめんのたまご x2\nいわのたまご x2\nはっぱのたまご x2\nウッディなたまご x2\nそらとぶたまご x2\nサカナのたまご x2",image: "CapHatEggparty0",
      name: "たまごのパーティーハット",get: "たまごでひらめくレシピをすべて覚える"},
    {category: 5,series: 0,obtain: 99,make: "じめんのたまご x3\nいわのたまご x3\nはっぱのたまご x3\nウッディなたまご x3\nそらとぶたまご x3\nサカナのたまご x3",image: "TopsTexOnepieceBalloonLEgg0"
      ,name: "たまごのパーティーワンピ",get: "たまごでひらめくレシピをすべて覚える"},
    {category: 1,series: 99,obtain: 2,make: "もくざい x5\nてっこうせき x2",image: "FtrPirateBarrel",name: "たる",get: get2},
    {category: 1,series: 99,obtain: 10,make: "もくざい x3\nかたいもくざい x3\nやわらかいもくざい x3\nてっこうせき x2",image: "FtrWorkbenchS_Remake_0_0",name: "ちいさなDIYさぎょうだい",get: get10},
    {category: 2,series: 6,obtain: 12,make: "まつぼっくり x6\nどんぐり x4\nかたいもくざい x1",image: "FtrNutTreeS_Remake_0_0",name: "ちいさなきのみのツリー",get: balloon},
    {category: 4,series: 99,obtain: 3,make: "いし x10",image: "RoomTexFloorBasement00",name: "ちかしつのゆか",get: get3},
    {category: 4,series: 2,obtain: 12,make: "はるのわかたけ x7\nたけのこ x3",image: "RoomTexWallChikurin00",name: "ちくりんのかべ",get: balloon},
    {category: 4,series: 99,obtain: 7,make: "やわらかいもくざい x15",image: "RoomTexWallHerringbone00",name: "ちゃいろいヘリンボーンのかべ",get: get7},
    {category: 1,series: 11,obtain: 13,make: "ほしのかけら x10\nてっこうせき x15",image: "FtrModule",name: "ちゃくりくせん",get: get13},
    {category: 1,series: 99,obtain: 2,make: "かたいもくざい x12",image: "FtrDiningtableJapan_Remake_0_0",name: "ちゃぶだい",get: get2},
    {category: 1,series: 99,obtain: 3,make: "しょるいのやま x1",image: "FtrFloorpapers_Remake_0_0",name: "ちらばったかみ",get: get3},
    {category: 1,series: 11,obtain: 13,make: "ほしのかけら x15\nおおきなほしのかけら x1",image: "FtrMoon",name: "つき",get: get13},
    {category: 2,series: 99,obtain: 0,make: "ほん x5",image: "FtrBooks_Remake_0_0",name: "つまれたほん",get: get0},
    {category: 1,series: 99,obtain: 11,make: "タイヤ x3",image: "FtrTyres_Remake_0_0",name: "つまれたタイヤ",get: "タイヤを３つ釣る"},
    {category: 2,series: 99,obtain: 9,make: "やわらかいもくざい x3",image: "FtrBlockBrick_Remake_0_0",name: "やわらかいもくざい x3",get: get9},
    {category: 3,series: 99,obtain: 5,make: "つみきのおもちゃ x1\nやわらかいもくざい x2\nてっこうせき x1",image: "FtrBlockClock_Remake_0_0",name: "つみきウォールクロック",get: get5},
    {category: 1,series: 99,obtain: 9,make: "つみきのおもちゃ x1\nやわらかいもくざい x5\nてっこうせき x2",image: "FtrBlockCompo_Remake_0_0",name: "つみきコンポ",get: get9},
    {category: 1,series: 99,obtain: 5,make: "つみきのおもちゃ x1\nやわらかいもくざい x2",image: "FtrBlockStoolS_Remake_0_0",name: "つみきスツール",get: get5},
    {category: 1,series: 99,obtain: 9,make: "つみきのおもちゃ x1\nやわらかいもくざい x3",image: "FtrBlockChairS_Remake_0_0",name: "つみきチェア",get: get9},
    {category: 1,series: 99,obtain: 4,make: "つみきのおもちゃ x1\nやわらかいもくざい x12",image: "FtrBlockChest_Remake_0_0",name: "つみきチェスト",get: get4},
    {category: 1,series: 99,obtain: 7,make: "つみきのおもちゃ x1\nやわらかいもくざい x8",image: "FtrBlockTableL_Remake_0_0",name: "つみきテーブル",get: get7},
    {category: 1,series: 99,obtain: 9,make: "つみきのおもちゃ x1\nやわらかいもくざい x3",image: "FtrBlockShelf_Remake_0_0",name: "つみきブックシェルフ",get: get9},
    {category: 1,series: 99,obtain: 4,make: "つみきのおもちゃ x1\nやわらかいもくざい x17",image: "FtrBlockBedS_Remake_0_0",name: "つみきベッド",get: get4},
    {category: 1,series: 99,obtain: 7,make: "つみきのおもちゃ x1\nやわらかいもくざい x4",image: "FtrBlockChairL_Remake_0_0",name: "つみきベンチ",get: get7},
    {category: 0,series: 99,obtain: 9,make: "ショボいつりざお x1\nてっこうせき x1",image: "ToolAngling_Remake_0_0",name: "つりざお",get: get9},
    {category: 1,series: 99,obtain: 0,make: "かたいもくざい x2\nやわらかいもくざい x6",image: "FtrKatakatatoy_Remake_0_0",name: "ておしぐるま",get: get0},
    {category: 1,series: 99,obtain: 0,make: "てっこうせき x2\nねんど x6",image: "FtrHandpump_Remake_0_0",name: "ておしポンプ",get: get0},
    {category: 1,series: 99,obtain: 1,make: "てっこうせき x20",image: "FtrIronframe_Remake_0_0",name: "てっこつ",get: get1},
    {category: 4,series: 99,obtain: 3,make: "てっこうせき x8",image: "RoomTexWallSteel00",name: "てっこつのかべ",get: get3},
    {category: 4,series: 99,obtain: 3,make: "てっこうせき x7",image: "RoomTexFloorSteel00",name: "てっぱんのゆか",get: get3},
    {category: 6,series: 99,obtain: 10,make: "てっこうせき x6",image: "ItemFenceSteel",name: "てつのさく",get: get10},
    {category: 0,series: 99,obtain: 13,make: "てっこうせき x3\nほしのかけら x3",image: "ToolStickIron",name: "てつのステッキ",get: get13},
    {category: 2,series: 99,obtain: 6,make: "ねんど x4",image: "FtrPotteryjug_Remake_0_0",name: "とうきのジャグ",get: get6},
    {category: 1,series: 99,obtain: 3,make: "いし x18",image: "FtrStonelantern_Remake_0_0",name: "とうろう",get: get3},
    {category: 1,series: 99,obtain: 7,make: "もくざい x8",image: "FtrBirdcage_Remake_0_0",name: "とりかご",get: get7},
    {category: 1,series: 99,obtain: 2,make: "てっこうせき x6\nもくざい x5",image: "FtrTamtam_Remake_0_0",name: "どら",get: get2},
    {category: 5,series: 4,obtain: 12,make: "どんぐり x6",image: "BagShoulderAcorn0",name: "どんぐりポシェット",get: balloon},
    {category: 1,series: 2,obtain: 12,make: "はるのわかたけ x7\nもくざい x3",image: "FtrBambooSomen",name: "ながしそうめん",get: balloon},
    {category: 3,series: 99,obtain: 5,make: "もくざい x3",image: "FtrDoorOrnamentPaw_Remake_0_0",name: "にくきゅうのドアプレート",get: get5},
    {category: 2,series: 99,obtain: 2,make: "ねんど x2",image: "FtrClaytoy_Remake_0_0",name: "ねんどのおもちゃ",get: get2},
    {category: 0,series: 99,obtain: 9,make: "もくざい x4\nかたいもくざい x4\nやわらかいもくざい x4",image: "ToolLadder",name: "はしご",get: get9},
    {category: 5,series: 99,obtain: 1,make: "ざっそう x5",image: "AccessoryMouthLeafGreen",name: "はっぱ",get: get1},
    {category: 5,series: 99,obtain: 5,make: "ざっそう x10",image: "CapMaskLeaf0",name: "はっぱのおめん",get: get5},
    {category: 5,series: 99,obtain: 7,make: "ざっそう x15",image: "UmbrellaLeaf0Cropped",name: "はっぱのかさ",get: get7},
    {category: 5,series: 0,obtain: 99,make: "はっぱのたまご x2",image: "CapHatEggleaf0",name: "はっぱのたまごのから",get: "はっばのたまごを集める"},
    {category: 5,series: 0,obtain: 99,make: "はっぱのたまご x2",image: "ShoesLowcutEggleaf0",name: "はっぱのたまごのくつ",get: "はっばのたまごを集める"},
    {category: 5,series: 0,obtain: 99,make: "はっぱのたまご x3",image: "TopsTexOnepieceRibNEggleaf0",name: "はっぱのたまごのからふく",get: "はっばのたまごを集める"},
    {category: 1,series: 99,obtain: 6,make: "いし x20",image: "FtrGardenrockLow",name: "ひくいにわいし",get: get6},
    {category: 1,series: 99,obtain: 0,make: "ダンボール x5",image: "FtrMovingboxL",name: "ひっこしダンボールL",get: get0},
    {category: 1,series: 99,obtain: 0,make: "ダンボール x4",image: "FtrMovingboxM",name: "ひっこしダンボールM",get: get0},
    {category: 1,series: 99,obtain: 5,make: "ダンボール x2",image: "FtrMovingboxS",name: "ひっこしダンボールS",get: get5},
    {category: 4,series: 7,obtain: 12,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x8",image: "RoomTexWallIceFloe00",name: "ひょうざんのかべ",get: balloon},
    {category: 2,series: 0,obtain: 99,make: "じめんのたまご x4\nいわのたまご x4\nはっぱのたまご x4\nウッディなたまご x4\nそらとぶたまご x4\nサカナのたまご x4",image: "FtrDollPyn",name: "ぴょんたろうのおきあがりこぼし",get: "ぴょんたろう"},
    {category: 4,series: 99,obtain: 3,make: "かたいもくざい x15",image: "RoomTexWallCedar00",name: "ふしありウッドウォール",get: get3},
    {category: 1,series: 99,obtain: 0,make: "かたいもくざい x8",image: "FtrMusicstand_Remake_0_0",name: "ふめんだい",get: get0},
    {category: 1,series: 99,obtain: 10,make: "みずのみば x1\nいし x20\nてっこうせき x8",image: "FtrFountain_Remake_0_0",name: "ふんすい",get: get10},
    {category: 1,series: 99,obtain: 9,make: "ざっそう x20",image: "FtrHaybed_Remake_0_0",name: "ほしくさのベッド",get: get9},
    {category: 4,series: 11,obtain: 13,make: "ほしのかけら x5\nおおきなほしのかけら x1",image: "RoomSpWallStarSky00",name: "ほしぞらのかべ",get: get13},
    {category: 4,series: 3,obtain: 12,make: "なつのかいがら x3\nすなはまのゆか x1",image: "RoomTexFloorSandStar00",name: "ほしのすなはまのゆか",get: balloon},
    {category: 1,series: 99,obtain: 2,make: "さくらのぼんさい x1\nマツのぼんさい x1\nもくざい x8",image: "FtrBonsaiShelf",name: "ぼんさいだな",get: get2},
    {category: 2,series: 99,obtain: 1,make: "もくざい x8",image: "FtrFirewood",name: "まき",get: get1},
    {category: 1,series: 99,obtain: 4,make: "まるたのベンチ x2\nかたいもくざい x3",image: "FtrLogShelf_Remake_0_0",name: "まるたのかざりだな",get: get4},
    {category: 3,series: 99,obtain: 0,make: "かたいもくざい x2\nてっこうせき x1",image: "FtrLogClockWall_Remake_0_0",name: "まるたのかべかけどけい",get: get0},
    {category: 1,series: 99,obtain: 3,make: "もくざい x3",image: "FtrWoodPile_Remake_0_0",name: "まるたのくい",get: get3},
    {category: 6,series: 99,obtain: 10,make: "かたいもくざい x6",image: "ItemFenceLog",name: "まるたのさく",get: get10},
    {category: 1,series: 99,obtain: 5,make: "かたいもくざい x12",image: "FtrLogBedS_Remake_0_0",name: "まるたのガーデンベッド",get: get5},
    {category: 1,series: 99,obtain: 5,make: "もくざい x4",image: "FtrLogStoolS_Remake_0_0",name: "まるたのスツール",get: get5},
    {category: 1,series: 99,obtain: 4,make: "かたいもくざい x8",image: "FtrLogSofaS_Remake_0_0",name: "まるたのソファ",get: get4},
    {category: 1,series: 99,obtain: 2,make: "かたいもくざい x15",image: "FtrLogTableL_Remake_0_0",name: "まるたのダイニングテーブル",get: get2},
    {category: 1,series: 99,obtain: 5,make: "かたいもくざい x30",image: "FtrLogBedW_Remake_0_0",name: "まるたのベッド",get: get5},
    {category: 1,series: 99,obtain: 4,make: "かたいもくざい x8",image: "FtrLogStoolL_Remake_0_0",name: "まるたのベンチ",get: get4},
    {category: 1,series: 99,obtain: 5,make: "かたいもくざい x15",image: "FtrLogTableLRound_Remake_0_0",name: "まるたのラウンドテーブル",get: get5},
    {category: 1,series: 99,obtain: 4,make: "まるたのソファ x2",image: "FtrLogSofaL_Remake_0_0",name: "まるたのロングソファ",get: get4},
    {category: 1,series: 11,obtain: 13,make: "ほしのかけら x7\nおおきなほしのかけら x1",image: "FtrStarMoonChairL_Remake_0_0",name: "みかづきチェア",get: get13},
    {category: 1,series: 99,obtain: 10,make: "いし x8\nてっこうせき x2",image: "FtrDrinkingfountain_Remake_0_0",name: "みずのみば",get: get10},
    {category: 1,series: 99,obtain: 0,make: "かたいもくざい x2\nやわらかいもくざい x3",image: "FtrSignpost_Remake_0_0",name: "みちしるべ",get: get0},
    {category: 1,series: 2,obtain: 12,make: "はるのわかたけ x1\nざっそう x10",image: "FtrFallenleavesGreen",name: "みどりのおちば",get: balloon},
    {category: 5,series: 99,obtain: 5,make: "ざっそう x7",image: "BottomsTexSkirtBoxGrass1",name: "みどりのこしみの",get: get5},
    {category: 4,series: 3,obtain: 12,make: "なつのかいがら x5",image: "RoomSpWallTropical00",name: "みなみのうみなかべ",get: balloon},
    {category: 4,series: 3,obtain: 12,make: "なつのかいがら x6",image: "RoomSpFloorWater00",name: "みなものゆか",get: balloon},
    {category: 5,series: 99,obtain: 4,make: "ざっそう x8",image: "TopsTexTopCoatLStrawBeige",name: "みの",get: get4},
    {category: 3,series: 99,obtain: 8,make: "むらさきのヒヤシンス x10",image: "FtrDoorOrnamentWreathHyacinthRare",name: "むらさきのヒヤシンスのリース",get: get8},
    {category: 2,series: 99,obtain: 9,make: "もくざい x3",image: "FtrMokugyo_Remake_0_0",name: "もくぎょ",get: get9},
    {category: 1,series: 99,obtain: 7,make: "もくざい x4",image: "FtrTrashboxWood_Remake_0_0",name: "もくせいのくずかご",get: get7},
    {category: 2,series: 99,obtain: 4,make: "やわらかいもくざい x4\nてっこうせき x2",image: "FtrToolboxWood_Remake_0_0",name: "もくせいのこうぐばこ",get: get4},
    {category: 1,series: 99,obtain: 5,make: "もくざい x5\nてっこうせき x1",image: "FtrWoodenMirror_Remake_0_0",name: "もくせいのすがたみ",get: get5},
    {category: 1,series: 99,obtain: 0,make: "ほん x5\nもくざい x10",image: "FtrBookshelf_Remake_0_0",name: "もくせいのほんだな",get: get0},
    {category: 1,series: 99,obtain: 3,make: "もくざい x3\nてっこうせき x1",image: "FtrBucketWood",name: "もくせいのバケツ",get: get3},
    {category: 1,series: 99,obtain: 99,make: "もくざい x12",image: "FtrWoodenCloset_Remake_0_0",name: "もくせいクロゼット",get: "たぬきち"},
    {category: 1,series: 99,obtain: 6,make: "もくざい x8",image: "FtrWoodenTableS_Remake_0_0",name: "もくせいサイドテーブル",get: get6},
    {category: 1,series: 99,obtain: 0,make: "もくざい x18",image: "FtrWoodenBedS_Remake_0_0",name: "もくせいシングルベッド",get: get0},
    {category: 1,series: 99,obtain: 5,make: "もくざい x4",image: "FtrWoodenStoolS_Remake_0_0",name: "もくせいスツール",get: get5},
    {category: 1,series: 99,obtain: 3,make: "もくざい x30",image: "FtrWoodenBedW_Remake_0_0",name: "もくせいダブルベッド",get: get3},
    {category: 1,series: 99,obtain: 6,make: "もくざい x6",image: "FtrWoodenChairS_Remake_0_0",name: "もくせいチェア",get: get6},
    {category: 1,series: 99,obtain: 0,make: "もくざい x16",image: "FtrWoodenChest_Remake_0_0",name: "もくせいチェスト",get: get0},
    {category: 1,series: 99,obtain: 7,make: "もくざい x15",image: "FtrWoodenTableL_Remake_0_0",name: "もくせいテーブル",get: get7},
    {category: 2,series: 99,obtain: 7,make: "もくざい x3\nてっこうせき x1",image: "FtrWoodenMirrorS_Remake_0_0",name: "もくせいテーブルミラー",get: get7},
    {category: 1,series: 99,obtain: 7,make: "もくざい x6",image: "FtrWoodenTableMini_Remake_0_0",name: "もくせいミニテーブル",get: get7},
    {category: 1,series: 99,obtain: 3,make: "もくざい x10",image: "FtrWoodenTableM_Remake_0_0",name: "もくせいローテーブル",get: get3},
    {category: 1,series: 99,obtain: 4,make: "やわらかいもくざい x5",image: "FtrRockinghorse_Remake_0_0",name: "もくば",get: get4},
    {category: 1,series: 99,obtain: 2,make: "きのえだ x10",image: "FtrClothesline_Remake_0_0",name: "ものほしロープ",get: get2},
    {category: 5,series: 6,obtain: 12,make: "もみじのはっぱ x7",image: "UmbrellaAutumn0Cropped",name: "もみじのかさ",get: balloon},
    {category: 5,series: 6,obtain: 12,make: "もみじのはっぱ x6",image: "BagShoulderMaple0",name: "もみじのポシェット",get: balloon},
    {category: 2,series: 6,obtain: 12,make: "どんぐり x4\nかたいもくざい x2",image: "FtrBalancingtoy",name: "やじろべえ",get: balloon},
    {category: 1,series: 99,obtain: 10,make: "もくざい x12",image: "FtrFloat_Remake_0_0",name: "やたい",get: get10},
    {category: 6,series: 99,obtain: 10,make: "かたいもくざい x3\nてっこうせき x2",image: "ItemFenceBarbedWire",name: "ゆうしてっせん",get: get10},
    {category: 1,series: 11,obtain: 13,make: "ほしのかけら x10\nてっこうせき x20",image: "FtrSpacecraft",name: "ゆうじんうちゅうせん",get: get13},
    {category: 5,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x5",image: "CapCostumeSnowball0",name: "ゆきだるまのぼうし",get: "ゆきだるま"},
    {category: 3,series: 7,obtain: 12,make: "ゆきのけっしょう x4",image: "FtrDoorOrnamentWreathIce",name: "ゆきのけっしょうのリース",get: balloon},
    {category: 1,series: 8,obtain: 12,make: "あおいオーナメント x9\nきんこうせき x3",image: "FtrIllumiSnow_Remake_0_0",name: "ゆきのイルミネーション",get: balloon},
    {category: 6,series: 99,obtain: 10,make: "いし x6\nてっこうせき x3",image: "ItemFenceIronAndStone",name: "ようふうのさく",get: get10},
    {category: 1,series: 99,obtain: 4,make: "いし x30",image: "FtrGravestoneEuropean_Remake_0_0",name: "ようふうのはかいし",get: get4},
    {category: 1,series: 99,obtain: 1,make: "ハチのす x3\nもくざい x5",image: "FtrBeekeepingbox_Remake_0_0",name: "ようほうばこ",get: get1},
    {category: 1,series: 99,obtain: 0,make: "いし x15",image: "FtrGardenrock",name: "よくあるにわいし",get: get0},
    {category: 6,series: 99,obtain: 10,make: "もくざい x6",image: "ItemFenceHorizontalWood",name: "よこいたのさく",get: get10},
    {category: 4,series: 99,obtain: 4,make: "もくざい x15",image: "RoomTexWallMixPlankWood00",name: "よせぎのかべ",get: get4},
    {category: 4,series: 7,obtain: 12,make: "ゆきのけっしょう x10",image: "RoomSpFloorIceFloe00",name: "りゅうひょうのゆか",get: balloon},
    {category: 1,series: 99,obtain: 10,make: "いし x20\nスコップ x1",image: "FtrOpenairbath_Remake_0_0",name: "ろてんぶろ",get: get10},
    {category: 2,series: 99,obtain: 9,make: "もくざい x2\nやわらかいもくざい x2",image: "FtrQuoits_Remake_0_0",name: "わなげ",get: get9},
    {category: 6,series: 99,obtain: 10,make: "てっこうせき x3\nねんど x3\nいし x3",image: "ItemFenceJapanese",name: "わふうのさく",get: get10},
    {category: 1,series: 99,obtain: 0,make: "いし x30",image: "FtrGravestoneJapan_Remake_0_0",name: "わふうのはかいし",get: get0},
    {category: 6,series: 99,obtain: 10,make: "ざっそう x10\nもくざい x3",image: "ItemFenceDriedStraw",name: "わらぼしのさく",get: get10},
    {category: 3,series: 99,obtain: 7,make: "てっこうせき x2",image: "FtrDoorOrnamentIron_Remake_0_0",name: "アイアンなドアプレート",get: get7},
    {category: 5,series: 99,obtain: 2,make: "てっこうせき x8",image: "TopsTexOnepieceOverallLPlatearmorIron",name: "アイアンアーマー",get: get2},
    {category: 5,series: 99,obtain: 2,make: "てっこうせき x4",image: "ShoesKneeKnightIron",name: "アイアンアーマーシューズ",get: get2},
    {category: 5,series: 99,obtain: 2,make: "てっこうせき x5",image: "CapFullfaceKnightIron",name: "アイアンアーマーヘルメット",get: get2},
    {category: 3,series: 99,obtain: 3,make: "てっこうせき x3\nねんど x1",image: "FtrIronShelfW_Remake_0_0",name: "アイアンウォールラック",get: get3},
    {category: 3,series: 99,obtain: 9,make: "てっこうせき x4\nねんど x2",image: "FtrIronLampW_Remake_0_0",name: "アイアンウォールランプ",get: get9},
    {category: 1,series: 99,obtain: 2,make: "もくざい x12\nてっこうせき x6\nちいさなDIYさぎょうだい x1",image: "FtrWorkbenchIronwood_Remake_0_0",name: "アイアンウッドDIYテーブル",get: get2},
    {category: 1,series: 99,obtain: 6,make: "もくざい x12\nてっこうせき x6\nアイアンウッドチェスト x1",image: "FtrIronwoodCupboard_Remake_0_0",name: "アイアンウッドカップボード",get: get6},
    {category: 1,series: 99,obtain: 9,make: "もくざい x4\nてっこうせき x3\nアイアンウッドチェスト x1\nカッティングボード x1",image: "FtrIronwoodKitchen_Remake_0_0",name: "アイアンウッドキッチン",get: get9},
    {category: 3,series: 99,obtain: 3,make: "もくざい x2\nてっこうせき x2",image: "FtrIronwoodClockW_Remake_0_0",name: "アイアンウッドクロック",get: get3},
    {category: 1,series: 99,obtain: 3,make: "もくざい x3\nてっこうせき x2",image: "FtrIronwoodChairS_Remake_0_0",name: "アイアンウッドチェア",get: get3},
    {category: 1,series: 99,obtain: 6,make: "もくざい x7\nてっこうせき x4",image: "FtrIronwoodChest_Remake_0_0",name: "アイアンウッドチェスト",get: get6},
    {category: 1,series: 99,obtain: 2,make: "もくざい x12\nてっこうせき x6",image: "FtrIronwoodTableL_Remake_0_0",name: "アイアンウッドテーブル",get: get2},
    {category: 1,series: 99,obtain: 3,make: "もくざい x20\nてっこうせき x10",image: "FtrIronwoodBedS_Remake_0_0",name: "アイアンウッドベッド",get: get3},
    {category: 1,series: 99,obtain: 6,make: "もくざい x6\nてっこうせき x4",image: "FtrIronwoodTableM_Remake_0_0",name: "アイアンウッドローテーブル",get: get6},
    {category: 1,series: 99,obtain: 3,make: "もくざい x6\nてっこうせき x4",image: "FtrIronwoodServingcart_Remake_0_0",name: "アイアンウッドワゴン",get: get3},
    {category: 1,series: 99,obtain: 7,make: "てっこうせき x3",image: "FtrIrongardenChair_Remake_0_0",name: "アイアンガーデンチェア",get: get7},
    {category: 1,series: 99,obtain: 7,make: "てっこうせき x5",image: "FtrIrongardenTable_Remake_0_0",name: "アイアンガーデンテーブル",get: get7},
    {category: 1,series: 99,obtain: 7,make: "てっこうせき x8",image: "FtrIrongardenBench_Remake_0_0",name: "アイアンガーデンベンチ",get: get7},
    {category: 1,series: 99,obtain: 7,make: "てっこうせき x12",image: "FtrIronClosetLR_Remake_0_0",name: "アイアンクロゼット",get: get7},
    {category: 1,series: 99,obtain: 7,make: "てっこうせき x14",image: "FtrIronShelf_Remake_0_0",name: "アイアンシェルフ",get: get7},
    {category: 1,series: 99,obtain: 2,make: "てっこうせき x3",image: "FtrIronHanger_Remake_0_0",name: "アイアンハンガースタンド",get: get2},
    {category: 1,series: 99,obtain: 7,make: "てっこうせき x10",image: "FtrIronTableM_Remake_0_0",name: "アイアンワークテーブル",get: get7},
    {category: 4,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x8",image: "RoomSpWallIce00",name: "アイスなかべがみ",get: "ゆきだるま"},
    {category: 4,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x8",image: "RoomSpFloorIce00",name: "アイスなゆか",get: "ゆきだるま"},
    {category: 2,series: 7,obtain: 99,make: "ゆきのだいけっしょう x1\nゆきのけっしょう x1",image: "FtrIceCandy_Remake_0_0",name: "アイスキャンディー",get: "ゆきだるま"},
    {category: 1,series: 10,obtain: 13,make: "ほしのかけら x3\nみずがめざのかけら x2\nきんこうせき x2\nいし x5",image: "FtrZodiacAquarius",name: "アクエリアスのみずがめ",get: get13},
    {category: 1,series: 99,obtain: 3,make: "やわらかいもくざい x8\nてっこうせき x3",image: "FtrAcorsticguitar_Remake_0_0",name: "アコースティックギター",get: get3},
    {category: 1,series: 11,obtain: 13,make: "ほしのかけら x5\nてっこうせき x5",image: "FtrSpacesuit",name: "アストロノーツ",get: get13},
    {category: 5,series: 99,obtain: 8,make: "あかいアネモネ x2\nオレンジのアネモネ x2\nしろいアネモネ x2",image: "CapOrnamentAnemone1",name: "アネモネのかんむり",get: get8},
    {category: 5,series: 99,obtain: 8,make: "あおいアネモネ x3\nピンクのアネモネ x3",image: "CapOrnamentAnemone2",name: "アネモネのかんむり・クール",get: get8},
    {category: 5,series: 99,obtain: 8,make: "むらさきのアネモネ x6",image: "CapOrnamentAnemone3",name: "アネモネのかんむり・パープル",get: get8},
    {category: 2,series: 99,obtain: 0,make: "あかいアネモネ x3\nてっこうせき x2",image: "FtrFlowerFan_Remake_0_0",name: "アネモネのせんぷうき",get: get0},
    {category: 0,series: 99,obtain: 13,make: "オレンジのアネモネ x1\nほしのかけら x3",image: "ToolStickAnemones",name: "アネモネのステッキ",get: get13},
    {category: 3,series: 99,obtain: 8,make: "あかいアネモネ x3\nしろいアネモネ x3\nオレンジのアネモネ x3",image: "FtrDoorOrnamentWreathAnemone",name: "アネモネのリース",get: get8},
    {category: 1,series: 10,obtain: 13,make: "ほしのかけら x3\nおひつじざのかけら x2\nきんこうせき x1\nいし x5",image: "FtrZodiacAries",name: "アリエスのもくば",get: get13},
    {category: 2,series: 99,obtain: 6,make: "ねんど x3",image: "FtrAlomapot_Remake_0_0",name: "アロマポット",get: get6},
    {category: 4,series: 0,obtain: 12,make: "じめんのたまご x2\nいわのたまご x2\nはっぱのたまご x2\nウッディなたまご x2\nそらとぶたまご x2\nサカナのたまご x2",image: "RoomTexWallEaster00",name: "イースターなかべがみ",get: balloon},
    {category: 5,series: 0,obtain: 8,make: "じめんのたまご x1\nいわのたまご x1\nはっぱのたまご x1\nウッディなたまご x1\nそらとぶたまご x1\nサカナのたまご x1",image: "CapOrnamentCEgg0",name: "イースターなかんむり",get: get8+"<br>(季節限定)"},
    {category: 6,series: 0,obtain: 12,make: "じめんのたまご x1\nいわのたまご x1\nはっぱのたまご x1\nウッディなたまご x1\nそらとぶたまご x1\nサカナのたまご x1",image: "ItemFenceEgg",name: "イースターなさく",get: balloon},
    {category: 4,series: 0,obtain: 12,make: "じめんのたまご x2\nいわのたまご x2\nはっぱのたまご x2\nウッディなたまご x2\nそらとぶたまご x2\nサカナのたまご x2",image: "RoomTexFloorEaster00",name: "イースターなゆか",get: balloon},
    {category: 1,series: 0,obtain: 99,make: "じめんのたまご x2\nいわのたまご x2\nはっぱのたまご x2\nウッディなたまご x2\nそらとぶたまご x2\nサカナのたまご x2",image: "FtrEggArch",name: "イースターなアーチ",get: "ぴょんたろう"},
    {category: 3,series: 0,obtain: 12,make: "そらとぶたまご x3",image: "FtrEggClock",name: "イースターなウォールクロック",get: balloon},
    {category: 1,series: 0,obtain: 12,make: "いわのたまご x4",image: "FtrEggClosetLR",name: "イースターなクロゼット",get: balloon},
    {category: 1,series: 0,obtain: 12,make: "サカナのたまご x3",image: "FtrEggStool",name: "イースターなスツール",get: balloon},
    {category: 5,series: 0,obtain: 99,make: "ぴょんたろうのおきあがりこぼし x1\nほしのかけら x3",image: "ToolStickEgg",name: "イースターなステッキ",get: "ぴょんたろう"}
  ];
  function convertStr(str) {
    return str.replace(/[ァ-ン]/g, function(s) {
        return String.fromCharCode(s.charCodeAt(0) - 0x60);
    });
  }
  info.forEach((info) => {
    $("table").append(`
    <tr class="item" category="${info.category}" series="${info.series}" obtain="${info.obtain}" search="${convertStr(info.name)}" make="${info.make}">
      <td class="get-if"><div>未取得</div></td>
      <td class="dist-if"><div>不可</div></td>
      <td class="nos">
        <select>
          <option>--</option>
          <option>1</option>
          <option>2</option>
          <option>3</option>
          <option>4</option>
          <option>5</option>
          <option>6</option>
          <option>7</option>
          <option>8</option>
          <option>9</option>
        </select>
      </td>
      <td class="item-main-container">
        <div class="item-main">
          <img src="image/${info.image}.png">
          <div>${info.name}</div>
        </div>
      </td>
      <td class="howtoget">${info.get}</td>
    </tr>
    `)
  });

});
